export enum ResponseCode {
    // COMMON
    SUCCESS = "SUCCESS",
    INTERNAL_ERROR = "INTERNAL_ERROR",
    FAILED_TO_VALIDATE = "FAILED_TO_VALIDATE",
    INVALID_INPUT = "INVALID_INPUT",
    INVALID_ID = "INVALID_ID",
    INVALID_STATUS = "INVALID_STATUS",
    FORBIDDEN = "FORBIDDEN",

    // PAGINATION
    INVALID_PAGE = "INVALID_PAGE",

    // AUTH
    EMAIL_CONFLICT = "EMAIL_CONFLICT",
    PHONE_CONFLICT = "PHONE_CONFLICT",
    EMAIL_OR_PHONE_IS_REQUIRED = "EMAIL_OR_PHONE_IS_REQUIRED",
    INVALID_EMAIL = "INVALID_EMAIL",
    INVALID_PASSWORD = "INVALID_PASSWORD",
    INVALID_EMAIL_OR_PASSWORD = "INVALID_EMAIL_OR_PASSWORD",
    FAILED_TO_VALIDATE_USER = "FAILED_TO_VALIDATE_USER",
    USER_UNAUTHORIZED = "USER_UNAUTHORIZED",
    ROLE_NOT_FOUND = "ROLE_NOT_FOUND",
    INSUFFICIENT_ROLE = "INSUFFICIENT_ROLE",
    TOKEN_NOT_FOUND = "TOKEN_NOT_FOUND",
    TOKEN_INVALID_OR_EXPIRED = "TOKEN_INVALID_OR_EXPIRED",

    // FILE
    FILE_PATH_NOT_FOUND = "FILE_PATH_NOT_FOUND",
    FILE_NOT_FOUND = "FILE_NOT_FOUND",
    FAILED_TO_SAVE_FILE = "FAILED_TO_SAVE_FILE",
    FAILED_TO_READ_FILE = "FAILED_TO_READ_FILE",

    // DATE
    INVALID_DATE = "INVALID_DATE",

    // USER
    USER_NOT_FOUND = "USER_NOT_FOUND",

    FAILED_TO_CREATE_USER = "FAILED_TO_CREATE_USER",
    FAILED_TO_UPDATE_USER = "FAILED_TO_UPDATE_USER",
    FAILED_TO_DELETE_USER = "FAILED_TO_DELETE_USER",
    FAILED_TO_UPDATE_PASSWORD = "FAILED_TO_UPDATE_PASSWORD",
    FAILED_TO_FIND_USER = "FAILED_TO_FIND_USER",

    // REVIEW
    REVIEW_NOT_FOUND = "REVIEW_NOT_FOUND",
    FAILED_TO_CREATE_REVIEW = "FAILED_TO_CREATE_REVIEW",
    FAILED_TO_CREATE_REPLY = "FAILED_TO_CREATE_REPLY",
    FAILED_TO_DELETE_REVIEW = "FAILED_TO_DELETE_REVIEW",
    FAILED_TO_DELETE_REPLY = "FAILED_TO_DELETE_REPLY",
    FAILED_TO_APPROVE_REVIEW = "FAILED_TO_APPROVE_REVIEW",

    // ADDRESS
    ADDRESS_NOT_FOUND = "ADDRESS_NOT_FOUND",
    FAILED_TO_GET_PROVINCES = "FAILED_TO_GET_PROVINCES",
    FAILED_TO_GET_DISTRICTS = "FAILED_TO_GET_DISTRICTS",
    FAILED_TO_GET_WARDS = "FAILED_TO_GET_WARDS",
    FAILED_TO_GET_USER_ADDRESS = "FAILED_TO_GET_USER_ADDRESS",
    FAILED_TO_CREATE_USER_ADDRESS = "FAILED_TO_CREATE_USER_ADDRESS",
    FAILED_TO_CREATE_FARM_ADDRESS = "FAILED_TO_CREATE_FARM_ADDRESS",
    FAILED_TO_UPDATE_USER_ADDRESS = "FAILED_TO_UPDATE_USER_ADDRESS",

    // CATEGORY
    CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND",
    SUBCATEGORY_NOT_FOUND = "SUBCATEGORY_NOT_FOUND",
    FAILED_TO_GET_CATEGORY = "FAILED_TO_GET_CATEGORY",
    FAILED_TO_GET_SUBCATEGORY = "FAILED_TO_GET_SUBCATEGORY",
    FAILED_TO_CREATE_CATEGORY = "FAILED_TO_CREATE_CATEGORY",
    FAILED_TO_CREATE_SUBCATEGORY = "FAILED_TO_CREATE_SUBCATEGORY",

    // PRODUCT
    PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND",
    FAILED_TO_GET_PRODUCT = "FAILED_TO_GET_PRODUCT",
    FAILED_TO_CREATE_PRODUCT = "FAILED_TO_CREATE_PRODUCT",
    FAILED_TO_DELETE_PRODUCT = "FAILED_TO_DELETE_PRODUCT",
    FAILED_TO_UPDATE_PRODUCT = "FAILED_TO_UPDATE_PRODUCT",

    // BIOMETRIC
    FAILED_TO_VERIFY_BIOMETRIC = "FAILED_TO_VERIFY_BIOMETRIC",

    // FARM
    FARM_NOT_FOUND = "FARM_NOT_FOUND",
    FAILED_TO_REGISTER_FARM = "FAILED_TO_REGISTER_FARM",
    FARM_EXISTED = "FARM_EXISTED",
    FAILED_TO_GET_FARM = "FAILED_TO_GET_FARM",
    FAILED_TO_UPDATE_FARM = "FAILED_TO_UPDATE_FARM",

    // NOTIFICATION
    FAILED_TO_CREATE_USER_DEVICE = "FAILED_TO_CREATE_USER_DEVICE",
    FAILED_TO_REMOVE_USER_DEVICE = "FAILED_TO_REMOVE_USER_DEVICE",
    FAILED_TO_GET_USER_FCM_TOKEN = "FAILED_TO_GET_FCM_TOKEN",
    FAILED_TO_CREATE_CHANNEL = "FAILED_TO_CREATE_CHANNEL",
    FAILED_TO_DELETE_CHANNEL = "FAILED_TO_DELETE_CHANNEL",
    FAILED_TO_UPDATE_CHANNEL = "FAILED_TO_UPDATE_CHANNEL",
    FAILED_TO_GET_CHANNEL = "FAILED_TO_GET_CHANNEL",
    FAILED_TO_CREATE_TEMPLATE = "FAILED_TO_CREATE_TEMPLATE",
    FAILED_TO_UPDATE_TEMPLATE = "FAILED_TO_UPDATE_TEMPLATE",
    FAILED_TO_DELETE_TEMPLATE = "FAILED_TO_DELETE_TEMPLATE",
    FAILED_TO_GET_TEMPLATE = "FAILED_TO_GET_TEMPLATE",
    USER_PREFERENCE_NOT_FOUND = "USER_PREFERENCE_NOT_FOUND",
    FAILED_TO_GET_USER_PREFERENCE = "FAILED_TO_GET_USER_PREFERENCE",
    FAILED_TO_CREATE_USER_PREFERENCE = "FAILED_TO_CREATE_USER_PREFERENCE",
    FAILED_TO_UPDATE_USER_PREFERENCE = "FAILED_TO_UPDATE_USER_PREFERENCE",
    FAILED_TO_UPDATE_CHANNEL_SUBSCRIPTION = "FAILED_TO_UPDATE_CHANNEL_SUBSCRIPTION",


    // CROP MANAGEMENT
    // PLOT
    PLOT_NOT_FOUND = "PLOT_NOT_FOUND",
    FAILED_TO_GET_PLOTS = "FAILED_TO_GET_PLOTS",
    FAILED_TO_CREATE_PLOT = "FAILED_TO_CREATE_PLOT",
    FAILED_TO_UPDATE_PLOT = "FAILED_TO_UPDATE_PLOT",
    FAILED_TO_DELETE_PLOT = "FAILED_TO_DELETE_PLOT",
    FAILED_TO_GET_PLOT_DETAIL = "FAILED_TO_GET_PLOT_DETAIL",

    // SEASON
    FAILED_TO_CREATE_SEASON = "FAILED_TO_CREATE_SEASON",
    FAILED_TO_UPDATE_SEASON = "FAILED_TO_UPDATE_SEASON",
    FAILED_TO_FINISH_SEASON = "FAILED_TO_FINISH_SEASON",
    INVALID_SEASON_FOR_CROP_TYPE = "INVALID_SEASON_FOR_CROP_TYPE",

    // STEP
    FAILED_TO_ADD_STEP = "FAILED_TO_ADD_STEP",
    FAILED_TO_GET_STEPS = "FAILED_TO_GET_STEP",
    FAILED_TO_CREATE_STEP = "FAILED_TO_CREATE_STEP",
    INVALID_STEP_ORDER = "INVALID_STEP_ORDER",
    INVALID_STEP_FOR_CROP_TYPE = "INVALID_STEP_FOR_CROP_TYPE",
    PREVIOUS_STEP_IN_PROGRESS = "PREVIOUS_STEP_IN_PROGRESS",

    // LOG
    FAILED_TO_ADD_LOG = "FAILED_TO_ADD_LOG",
    FAILED_TO_GET_LOGS = "FAILED_TO_GET_LOGS",
    STEP_ALREADY_DONE = "STEP_ALREADY_DONE",
    NOT_ENOUGH_LOG = "NOT_ENOUGH_LOG",
}
