export enum ResponseCode {
    // COMMON
    SUCCESS = "SUCCESS",
    INTERNAL_ERROR = "INTERNAL_ERROR",
    FAILED_TO_VALIDATE = "FAILED_TO_VALIDATE",
    INVALID_INPUT = "INVALID_INPUT",
    INVALID_ID = "INVALID_ID",
    INVALID_STATUS = "INVALID_STATUS",

    // PAGINATION
    INVALID_PAGE = "INVALID_PAGE",

    // AUTH
    EMAIL_CONFLICT = "EMAIL_CONFLICT",
    PHONE_CONFLICT = "PHONE_CONFLICT",
    EMAIL_OR_PHONE_IS_REQUIRED = "EMAIL_OR_PHONE_IS_REQUIRED",
    INVALID_EMAIL = "INVALID_EMAIL",
    INVALID_PASSWORD = "INVALID_PASSWORD",
    INVALID_EMAIL_OR_PASSWORD = "INVALID_EMAIL_OR_PASSWORD",
    FAILED_TO_VALIDATE_USER = "FAILED_TO_VALIDATE_USER",
    USER_UNAUTHORIZED = "USER_UNAUTHORIZED",

    // USER
    USER_NOT_FOUND = "USER_NOT_FOUND",

    FAILED_TO_CREATE_USER = "FAILED_TO_CREATE_USER",
    FAILED_TO_UPDATE_USER = "FAILED_TO_UPDATE_USER",
    FAILED_TO_DELETE_USER = "FAILED_TO_DELETE_USER",
    FAILED_TO_UPDATE_PASSWORD = "FAILED_TO_UPDATE_PASSWORD",
    FAILED_TO_FIND_USER = "FAILED_TO_FIND_USER",

    // REVIEW
    REVIEW_NOT_FOUND = "REVIEW_NOT_FOUND",
    FAILED_TO_CREATE_REVIEW = "FAILED_TO_CREATE_REVIEW",
    FAILED_TO_CREATE_REPLY = "FAILED_TO_CREATE_REPLY",
    FAILED_TO_DELETE_REVIEW = "FAILED_TO_DELETE_REVIEW",
    FAILED_TO_DELETE_REPLY = "FAILED_TO_DELETE_REPLY",
    FAILED_TO_APPROVE_REVIEW = "FAILED_TO_APPROVE_REVIEW",

    // ADDRESS
    ADDRESS_NOT_FOUND = "ADDRESS_NOT_FOUND",
    FAILED_TO_GET_PROVINCES = "FAILED_TO_GET_PROVINCES",
    FAILED_TO_GET_DISTRICTS = "FAILED_TO_GET_DISTRICTS",
    FAILED_TO_GET_WARDS = "FAILED_TO_GET_WARDS",
    FAILED_TO_GET_USER_ADDRESS = "FAILED_TO_GET_USER_ADDRESS",
    FAILED_TO_CREATE_USER_ADDRESS = "FAILED_TO_CREATE_USER_ADDRESS",
    FAILED_TO_CREATE_FARM_ADDRESS = "FAILED_TO_CREATE_FARM_ADDRESS",
    FAILED_TO_UPDATE_USER_ADDRESS = "FAILED_TO_UPDATE_USER_ADDRESS",

    // CATEGORY
    CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND",
    SUBCATEGORY_NOT_FOUND = "SUBCATEGORY_NOT_FOUND",
    FAILED_TO_GET_CATEGORY = "FAILED_TO_GET_CATEGORY",
    FAILED_TO_GET_SUBCATEGORY = "FAILED_TO_GET_SUBCATEGORY",
    FAILED_TO_CREATE_CATEGORY = "FAILED_TO_CREATE_CATEGORY",
    FAILED_TO_CREATE_SUBCATEGORY = "FAILED_TO_CREATE_SUBCATEGORY",

    // PRODUCT
    PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND",
    FAILED_TO_GET_PRODUCT = "FAILED_TO_GET_PRODUCT",
    FAILED_TO_CREATE_PRODUCT = "FAILED_TO_CREATE_PRODUCT",
    FAILED_TO_DELETE_PRODUCT = "FAILED_TO_DELETE_PRODUCT",
    FAILED_TO_UPDATE_PRODUCT = "FAILED_TO_UPDATE_PRODUCT",

    // BIOMETRIC
    FAILED_TO_VERIFY_BIOMETRIC = "FAILED_TO_VERIFY_BIOMETRIC",

    // FARM
    FARM_NOT_FOUND = "FARM_NOT_FOUND",
    FAILED_TO_REGISTER_FARM = "FAILED_TO_REGISTER_FARM",
    FARM_EXISTED = "FARM_EXISTED",
    FAILED_TO_GET_FARM = "FAILED_TO_GET_FARM",
    FAILED_TO_UPDATE_FARM = "FAILED_TO_UPDATE_FARM",
}
