export enum ResponseCode {
    // COMMON
    SUCCESS = "SUCCESS",
    INTERNAL_ERROR = "INTERNAL_ERROR",
    FAILED_TO_VALIDATE = "FAILED_TO_VALIDATE",
    INVALID_INPUT = "INVALID_INPUT",
    INVALID_MEDIA_FILE_INPUT = "INVALID_MEDIA_FILE_INPUT",
    INVALID_ID = "INVALID_ID",
    INVALID_STATUS = "INVALID_STATUS",
    FORBIDDEN = "FORBIDDEN",
    NOT_FOUND = "NOT_FOUND",

    // VERIFICATION
    VERIFICATION_NOT_FOUND = "VERIFICATION_NOT_FOUND",
    MAX_ATTEMPTS_REACHED = "MAX_ATTEMPTS_REACHED",
    INVALID_VERIFICATION = "INVALID_VERIFICATION",
    VERIFICATION_FAILED = "VERIFICATION_FAILED",

    // PAGINATION
    INVALID_PAGE = "INVALID_PAGE",

    // AUTH
    EMAIL_CONFLICT = "EMAIL_CONFLICT",
    PHONE_CONFLICT = "PHONE_CONFLICT",
    EMAIL_OR_PHONE_IS_REQUIRED = "EMAIL_OR_PHONE_IS_REQUIRED",
    INVALID_EMAIL = "INVALID_EMAIL",
    INVALID_PASSWORD = "INVALID_PASSWORD",
    INVALID_EMAIL_OR_PASSWORD = "INVALID_EMAIL_OR_PASSWORD",
    FAILED_TO_VALIDATE_USER = "FAILED_TO_VALIDATE_USER",
    USER_UNAUTHORIZED = "USER_UNAUTHORIZED",
    ROLE_NOT_FOUND = "ROLE_NOT_FOUND",
    INSUFFICIENT_ROLE = "INSUFFICIENT_ROLE",
    TOKEN_NOT_FOUND = "TOKEN_NOT_FOUND",
    TOKEN_INVALID_OR_EXPIRED = "TOKEN_INVALID_OR_EXPIRED",
    FAILED_TO_REGISTER_USER = "FAILED_TO_REGISTER_USER",

    // FILE STORAGE
    FILE_PATH_NOT_FOUND = "FILE_PATH_NOT_FOUND",
    FILE_NOT_FOUND = "FILE_NOT_FOUND",
    FAILED_TO_UPLOAD_FILE = "FAILED_TO_UPLOAD_FILE",
    FAILED_TO_READ_FILE = "FAILED_TO_READ_FILE",
    STORAGE_IS_DISABLED = "STORAGE_IS_DISABLED",
    FAILED_TO_GET_SIGNED_URL = "FAILED_TO_GET_SIGNED_URL",

    // DATE
    INVALID_DATE = "INVALID_DATE",
    INPUT_DATE_EARLIER_THAN_CURRENT_DATE = "INPUT_DATE_EARLIER_THAN_CURRENT_DATE",

    // USER
    USER_NOT_FOUND = "USER_NOT_FOUND",

    FAILED_TO_CREATE_USER = "FAILED_TO_CREATE_USER",
    FAILED_TO_UPDATE_USER = "FAILED_TO_UPDATE_USER",
    FAILED_TO_DELETE_USER = "FAILED_TO_DELETE_USER",
    FAILED_TO_UPDATE_PASSWORD = "FAILED_TO_UPDATE_PASSWORD",
    FAILED_TO_FIND_USER = "FAILED_TO_FIND_USER",
    FAILED_TO_UPDATE_ROLE = "FAILED_TO_UPDATE_ROLE",

    // REVIEW
    REVIEW_NOT_FOUND = "REVIEW_NOT_FOUND",
    FAILED_TO_CREATE_REVIEW = "FAILED_TO_CREATE_REVIEW",
    FAILED_TO_CREATE_REPLY = "FAILED_TO_CREATE_REPLY",
    FAILED_TO_DELETE_REVIEW = "FAILED_TO_DELETE_REVIEW",
    FAILED_TO_DELETE_REPLY = "FAILED_TO_DELETE_REPLY",
    FAILED_TO_APPROVE_REVIEW = "FAILED_TO_APPROVE_REVIEW",

    // ADDRESS
    ADDRESS_NOT_FOUND = "ADDRESS_NOT_FOUND",
    FAILED_TO_GET_PROVINCES = "FAILED_TO_GET_PROVINCES",
    FAILED_TO_GET_DISTRICTS = "FAILED_TO_GET_DISTRICTS",
    FAILED_TO_GET_WARDS = "FAILED_TO_GET_WARDS",
    FAILED_TO_GET_USER_ADDRESS = "FAILED_TO_GET_USER_ADDRESS",
    FAILED_TO_CREATE_USER_ADDRESS = "FAILED_TO_CREATE_USER_ADDRESS",
    FAILED_TO_CREATE_FARM_ADDRESS = "FAILED_TO_CREATE_FARM_ADDRESS",
    FAILED_TO_UPDATE_USER_ADDRESS = "FAILED_TO_UPDATE_USER_ADDRESS",


    // CATEGORY
    CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND",
    SUBCATEGORY_NOT_FOUND = "SUBCATEGORY_NOT_FOUND",
    FAILED_TO_GET_CATEGORY = "FAILED_TO_GET_CATEGORY",
    FAILED_TO_GET_SUBCATEGORY = "FAILED_TO_GET_SUBCATEGORY",
    FAILED_TO_CREATE_CATEGORY = "FAILED_TO_CREATE_CATEGORY",
    FAILED_TO_CREATE_SUBCATEGORY = "FAILED_TO_CREATE_SUBCATEGORY",

    // PRODUCT
    PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND",
    FAILED_TO_GET_PRODUCT = "FAILED_TO_GET_PRODUCT",
    FAILED_TO_CREATE_PRODUCT = "FAILED_TO_CREATE_PRODUCT",
    FAILED_TO_DELETE_PRODUCT = "FAILED_TO_DELETE_PRODUCT",
    FAILED_TO_UPDATE_PRODUCT = "FAILED_TO_UPDATE_PRODUCT",
    INVALID_PRODUCT = "INVALID_PRODUCT",
    INVALID_PRODUCT_TO_UPDATE_STATUS = "INVALID_PRODUCT_TO_UPDATE_STATUS",
    INVALID_PRODUCT_TO_DELETE = "INVALID_PRODUCT_TO_DELETE",

    // QR
    FAILED_TO_GET_QR = "FAILED_TO_GET_QR",
    FAILED_TO_UPDATE_QR = "FAILED_TO_UPDATE_QR",
    QR_NOT_FOUND = "QR_NOT_FOUND",
    QR_NOT_ACTIVATED = "QR_NOT_ACTIVATED",
    QR_BLOCKED = "QR_BLOCKED",

    // BIOMETRIC
    FAILED_TO_VERIFY_BIOMETRIC = "FAILED_TO_VERIFY_BIOMETRIC",

    // FARM
    FARM_NOT_FOUND = "FARM_NOT_FOUND",
    FAILED_TO_REGISTER_FARM = "FAILED_TO_REGISTER_FARM",
    FARM_EXISTED = "FARM_EXISTED",
    FAILED_TO_GET_FARM = "FAILED_TO_GET_FARM",
    FAILED_TO_UPDATE_FARM = "FAILED_TO_UPDATE_FARM",
    FAILED_TO_UPDATE_FARM_STATUS = "FAILED_TO_UPDATE_FARM_STATUS",
    FAILED_TO_APPROVE_FARM = "FAILED_TO_APPROVE_FARM",

    FAILED_TO_GET_CERTIFICATES = "FAILED_TO_GET_CERTIFICATES",
    FAILED_TO_ADD_CERTIFICATE = "FAILED_TO_ADD_CERTIFICATE",
    FAILED_TO_UPDATE_CERTIFICATE = "FAILED_TO_UPDATE_CERTIFICATE",

    FAILED_TO_CREATE_APPROVAL = "FAILED_TO_CREATE_APPROVAL",
    FAILED_TO_GET_APPROVALS = "FAILED_TO_GET_APPROVALS",

    // NOTIFICATION
    FAILED_TO_CREATE_USER_DEVICE = "FAILED_TO_CREATE_USER_DEVICE",
    FAILED_TO_REMOVE_USER_DEVICE = "FAILED_TO_REMOVE_USER_DEVICE",
    FAILED_TO_GET_USER_FCM_TOKEN = "FAILED_TO_GET_FCM_TOKEN",
    FAILED_TO_CREATE_CHANNEL = "FAILED_TO_CREATE_CHANNEL",
    FAILED_TO_DELETE_CHANNEL = "FAILED_TO_DELETE_CHANNEL",
    FAILED_TO_UPDATE_CHANNEL = "FAILED_TO_UPDATE_CHANNEL",
    FAILED_TO_GET_CHANNEL = "FAILED_TO_GET_CHANNEL",
    FAILED_TO_CREATE_TEMPLATE = "FAILED_TO_CREATE_TEMPLATE",
    FAILED_TO_UPDATE_TEMPLATE = "FAILED_TO_UPDATE_TEMPLATE",
    FAILED_TO_DELETE_TEMPLATE = "FAILED_TO_DELETE_TEMPLATE",
    FAILED_TO_GET_TEMPLATE = "FAILED_TO_GET_TEMPLATE",
    USER_PREFERENCE_NOT_FOUND = "USER_PREFERENCE_NOT_FOUND",
    FAILED_TO_GET_USER_PREFERENCE = "FAILED_TO_GET_USER_PREFERENCE",
    FAILED_TO_CREATE_USER_PREFERENCE = "FAILED_TO_CREATE_USER_PREFERENCE",
    FAILED_TO_UPDATE_USER_PREFERENCE = "FAILED_TO_UPDATE_USER_PREFERENCE",
    FAILED_TO_UPDATE_CHANNEL_SUBSCRIPTION = "FAILED_TO_UPDATE_CHANNEL_SUBSCRIPTION",



    // order
    ORDER_NOT_FOUND = "ORDER_NOT_FOUND",
    FAILED_TO_CREATE_ORDER = "FAILED_TO_CREATE_ORDER",
    FAILED_TO_GET_ORDERS = "FAILED_TO_GET_ORDERS",
    FAILED_TO_GET_ORDER = "FAILED_TO_GET_ORDER",
    FAILED_TO_CREATE_PAYOS_PAYMENT = "FAILED_TO_CREATE_PAYOS_PAYMENT",
    INVALID_ORDER_DATA = "INVALID_ORDER_DATA",
    DELIVERY_ADDRESS_NOT_FOUND = "DELIVERY_ADDRESS_NOT_FOUND",
    PRODUCT_NOT_OPEN_FOR_SALE = "PRODUCT_NOT_OPEN_FOR_SALE",
    INVALID_ORDER_STATUS = "INVALID_ORDER_STATUS",
    DELIVERY_ALREADY_EXISTS = "DELIVERY_ALREADY_EXISTS",
    INVALID_ADDRESS_DATA = "INVALID_ADDRESS_DATA",
    FAILED_TO_CALCULATE_SHIPPING_FEE = "FAILED_TO_CALCULATE_SHIPPING_FEE",
    FAILED_TO_CONFIRM_ORDER_DELIVERY = "FAILED_TO_CONFIRM_ORDER_DELIVERY",

    //ghn
    INVALID_GHN_REQUEST = "INVALID_GHN_REQUEST",
    FAILED_TO_UPDATE_DELIVERY = "FAILED_TO_UPDATE_DELIVERY",
    // product 
    INSUFFICIENT_STOCK = "INSUFFICIENT_STOCK",

    // CROP MANAGEMENT
    // CROP
    CROP_NOT_FOUND = "CROP_NOT_FOUND",
    FAILED_TO_GET_CROPS = "FAILED_TO_GET_CROPS",

    // PLOT
    PLOT_NOT_FOUND = "PLOT_NOT_FOUND",
    FAILED_TO_GET_PLOTS = "FAILED_TO_GET_PLOTS",
    FAILED_TO_CREATE_PLOT = "FAILED_TO_CREATE_PLOT",
    FAILED_TO_UPDATE_PLOT = "FAILED_TO_UPDATE_PLOT",
    FAILED_TO_DELETE_PLOT = "FAILED_TO_DELETE_PLOT",
    FAILED_TO_GET_PLOT_DETAIL = "FAILED_TO_GET_PLOT_DETAIL",

    // SEASON
    SEASON_NOT_FOUND = "SEASON_NOT_FOUND",
    FAILED_TO_CREATE_SEASON = "FAILED_TO_CREATE_SEASON",
    FAILED_TO_UPDATE_SEASON = "FAILED_TO_UPDATE_SEASON",
    FAILED_TO_GET_SEASON = "FAILED_TO_UPDATE_SEASON",
    FAILED_TO_FINISH_SEASON = "FAILED_TO_FINISH_SEASON",
    INVALID_SEASON_FOR_CROP_TYPE = "INVALID_SEASON_FOR_CROP_TYPE",
    PREVIOUS_SEASON_IN_PROGRESS = "PREVIOUS_SEASON_IN_PROGRESS",
    SEASON_IS_NOT_STARTED = "SEASON_IS_NOT_STARTED",
    SEASON_IS_NOT_IN_PROGRESS = "SEASON_IS_NOT_IN_PROGRESS",
    FAILED_TO_ASSIGN_SEASON = "FAILED_TO_ASSIGN_SEASON",
    SEASON_IS_NOT_COMPLETED_TO_ASSIGN = "SEASON_IS_NOT_COMPLETED_TO_ASSIGN",

    // STEP
    STEP_NOT_FOUND = "STEP_NOT_FOUND",
    STEP_IS_NOT_UPLOADED = "STEP_IS_NOT_UPLOADED",
    FAILED_TO_UPDATE_STEP = "FAILED_TO_UPDATE_STEP",
    FAILED_TO_ADD_STEP = "FAILED_TO_ADD_STEP",
    FAILED_TO_GET_STEP = "FAILED_TO_GET_STEP",
    FAILED_TO_GET_STEPS = "FAILED_TO_GET_STEP",
    FAILED_TO_CREATE_STEP = "FAILED_TO_CREATE_STEP",
    INVALID_STEP_ORDER = "INVALID_STEP_ORDER",
    INVALID_STEP_FOR_CROP_TYPE = "INVALID_STEP_FOR_CROP_TYPE",
    PREVIOUS_STEP_IN_PROGRESS = "PREVIOUS_STEP_IN_PROGRESS",
    FAILED_TO_VERIFY_STEP = "FAILED_TO_VERIFY_STEP",
    INVALID_FIRST_STEP = "INVALID_FIRST_STEP",
    INVALID_STEP_FOR_CROP = "INVALID_STEP_FOR_CROP",

    // LOG
    LOG_NOT_FOUND = "LOG_NOT_FOUND",
    FAILED_TO_ADD_LOG = "FAILED_TO_ADD_LOG",
    FAILED_TO_GET_LOG = "FAILED_TO_GET_LOG",
    STEP_ALREADY_DONE = "STEP_ALREADY_DONE",
    NOT_ENOUGH_LOG = "NOT_ENOUGH_LOG",
    INVALID_LOG_TO_INACTIVE = "INVALID_LOG_TO_INACTIVE",
    INACTIVE_EXCEED = "INACTIVE_EXCEED",

    // BLOCKCHAIN
    FAILED_TO_UPLOAD_LOGS = "FAILED_TO_UPLOAD_LOGS",
    FAILED_TO_VERIFY_LOGS = "FAILED_TO_VERIFY_LOGS",

    // AUDITOR VERIFICATION
    AUDITOR_NOT_FOUND = "AUDITOR_NOT_FOUND",
    AUDITOR_ALREADY_REGISTERED = "AUDITOR_ALREADY_REGISTERED",
    VERIFICATION_REQUEST_NOT_FOUND = "VERIFICATION_REQUEST_NOT_FOUND",
    AUDITOR_NOT_ASSIGNED = "AUDITOR_NOT_ASSIGNED",
    VOTE_ALREADY_SUBMITTED = "VOTE_ALREADY_SUBMITTED",
    VERIFICATION_EXPIRED = "VERIFICATION_EXPIRED",
    STEP_HAS_PENDING_VERIFICATION = "STEP_HAS_PENDING_VERIFICATION",
    FAILED_TO_CREATE_VERIFICATION = "FAILED_TO_CREATE_VERIFICATION",
    FAILED_TO_SUBMIT_VOTE = "FAILED_TO_SUBMIT_VOTE",
    FAILED_TO_GET_VERIFICATION_PACKAGE = "FAILED_TO_GET_VERIFICATION_PACKAGE",

    // IMAGE VERIFICATION
    FAILED_TO_VERIFY_IMAGE = "FAILED_TO_VERIFY_IMAGE",
    FAILED_TO_COMPUTE_HASH = "FAILED_TO_COMPUTE_HASH",
    FAILED_TO_CHECK_DUPLICATES = "FAILED_TO_CHECK_DUPLICATES",
    FAILED_TO_GET_VERIFICATION_RESULT = "FAILED_TO_GET_VERIFICATION_RESULT",
    IMAGE_DUPLICATE_DETECTED = "IMAGE_DUPLICATE_DETECTED",
}
