export enum AuditorRegistryEvent {
    AUDITOR_REGISTERED = 'AUDITOR_REGISTERED',
    VERIFICATION_SUBMITTED = 'VERIFICATION_SUBMITTED',
    VERIFICATION_FINALIZED = 'VERIFICATION_FINALIZED',
    VERIFICATION_REQUESTED = 'VERIFICATION_REQUESTED',
    AUDITOR_SLASHED = 'AUDITOR_SLASHED',
}
