INSERT INTO "step" 
(name, description, "order", repeated, is_optional, min_logs, type, interval_date, min_day_duration, max_day_duration, crop_id)
VALUES 
(
    'Chuẩn bị đất trồng',
    'Giải phóng đất trồng trước 4–6 tháng, vệ sinh đồng ruộng sạch sẽ. Đối với đất chu kỳ 2 cần trồng 2–3 vụ cây họ đậu để cải tạo đất trước khi trồng bưởi.',
    11,
    false,
    true,
    1,
    'PREPARE',
    NULL,
    120,
    180,
    1
),
(
    'Đào hố và bón lót',
    'Đào hố trồng bưởi kích thước trung bình 60x60x60 cm, trộn đất mặt với phân chuồng hoai, lân, vôi và NPK để bón lót trước khi trồng khoảng 1 tháng.',
    12,
    false,
    true,
    1,
    'PREPARE',
    NULL,
    30,
    NULL,
    1
),
(
    'Trồng cây',
    'Trồng cây giống bưởi đúng thời vụ, đặt cây thẳng, lấp đất ngang mặt bầu và nén chặt gốc.',
    20,
    false,
    true,
    1,
    'PLANTING',
    NULL,
    NULL,
    NULL,
    1
),
(
    'Tưới nước',
    'Tưới nước cho cây bưởi sau trồng và trong suốt quá trình sinh trưởng, đảm bảo đủ ẩm và thoát nước tốt.',
    31,
    true,
    false,
    1,
    'CARE',
    NULL,
    1,
    NULL,
    1
),
(
    'Bón phân',
    'Bón phân hữu cơ và vô cơ phù hợp từng giai đoạn sinh trưởng, tránh bón quá liều hoặc quá gần thời điểm thu hoạch.',
    32,
    true,
    false,
    1,
    'CARE',
    NULL,
    1,
    NULL,
    1
),
(
    'Cắt tỉa và tạo tán',
    'Cắt tỉa cành để tạo tán thông thoáng, khống chế chiều cao cây, thuận lợi cho chăm sóc và thu hoạch.',
    33,
    true,
    false,
    1,
    'CARE',
    NULL,
    1,
    NULL,
    1
),
(
    'Quản lý dịch hại',
    'Áp dụng các biện pháp canh tác, cơ học, sinh học và hóa học để phòng trừ sâu bệnh theo VietGAP.',
    34,
    true,
    false,
    1,
    'CARE',
    NULL,
    1,
    NULL,
    1
),
(
    'Thu hoạch',
    'Thu hoạch khi quả đạt độ chín phù hợp, đảm bảo thời gian cách ly thuốc BVTV và không làm xây xát quả.',
    40,
    false,
    false,
    1,
    'HARVEST',
    NULL,
    NULL,
    NULL,
    1
),
(
    'Đóng gói',
    'Bao gói quả bưởi sau thu hoạch theo đúng yêu cầu vệ sinh, đảm bảo độ đồng đều kích cỡ và không gây ô nhiễm sản phẩm.',
    50,
    false,
    false,
    1,
    'POST_HARVEST',
    NULL,
    NULL,
    NULL,
    1
);