INSERT INTO "step"
(name, description, "order", repeated, is_optional, min_logs, type, interval_date, min_day_duration, max_day_duration, crop_id)
VALUES
(
    'Chuẩn bị đất trồng',
    'Đất trồng mới cây cam cần được giải phóng trước từ 4–6 tháng. Nếu là đất chu kỳ 2 nên trồng 2–3 vụ cây họ đậu để cải tạo đất, trước khi trồng cần vệ sinh đồng ruộng sạch sẽ.',
    11,
    false,
    true,
    1,
    'PREPARE',
    NULL,
    120,
    180,
    2
),
(
    'Đào hố và bón lót',
    'Sau khi thiết kế vườn tiến hành đào hố và bón lót trước lúc trồng cây khoảng 1 tháng. Hố trồng cam thông thường có kích thước 60 × 60 × 60 cm. Đất đào lên được trộn đều với phân chuồng hoai mục, vôi, lân và NPK để bón lót, lấp trên mặt hố cao hơn mặt đất vườn 15–20 cm.',
    12,
    false,
    true,
    1,
    'PREPARE',
    NULL,
    30,
    NULL,
    2
),
(
    'Trồng cây',
    'Khi trồng, đào lỗ giữa mô, xé bỏ túi bầu polymer. Đối với đất bằng đặt bầu cây con sao cho mặt bầu cao hơn mặt mô 3–5 cm; đối với đất đồi đặt bầu cây con ngay trên mặt đất. Dùng tay ấn nén đất xung quanh bầu cây tạo sự liên kết giữa đất ngoài và bầu cây. Khi đặt cây phải xoay hướng cành ghép theo chiều gió, cắm cọc giữ cây; trồng xong tưới đẫm nước và tủ gốc bằng cỏ mục hoặc rơm rạ khô.',
    20,
    false,
    true,
    1,
    'PLANTING',
    NULL,
    NULL,
    NULL,
    2
),
(
    'Tưới nước',
    'Sau khi trồng phải tưới nước thường xuyên giữ ẩm trong vòng 20 ngày đến 1 tháng để cây hoàn toàn bén rễ và phục hồi. Sau đó tùy điều kiện thời tiết khô hạn mà tưới bổ sung nước cho cây.',
    31,
    true,
    false,
    1,
    'CARE',
    NULL,
    1,
    NULL,
    2
),
(
    'Làm cỏ và quản lý cỏ dại',
    'Những năm đầu cây còn nhỏ chưa giao tán cần làm sạch cỏ gốc thường xuyên theo hình chiếu của tán cây. Phần cỏ còn lại trong vườn được giữ để giữ ẩm, chống xói mòn và rửa trôi. Áp dụng biện pháp cắt cỏ để trả lại phân xanh cho đất, không sử dụng thuốc trừ cỏ trong vườn cam do bộ rễ cây cam rất mẫn cảm.',
    31,
    true,
    false,
    1,
    'CARE',
    NULL,
    1,
    NULL,
    2
),
(
    'Bón phân',
    'Bón phân cho cây cam theo từng giai đoạn sinh trưởng. Thời kỳ kiến thiết cơ bản có thể bón lót vào cuối năm và bón thúc chia làm nhiều lần trong năm. Sử dụng phân hữu cơ, phân hữu cơ vi sinh, phân lân, vôi và phân NPK tổng hợp theo hướng dẫn kỹ thuật VietGAP.',
    33,
    true,
    false,
    1,
    'CARE',
    NULL,
    1,
    NULL,
    2
),
(
    'Cắt tỉa và tạo tán',
    'Việc cắt tỉa, tạo tán được tiến hành ngay từ khi trồng xong. Bấm ngọn để cây ra lộc đồng đều, chọn 2–3 cành khỏe phân bố đều làm cành cấp 1, tiếp tục tạo cành cấp 2, cấp 3; cắt bỏ các cành mọc xiên vào trong tán nhằm tạo tán thông thoáng cho cây cam.',
    34,
    true,
    false,
    1,
    'CARE',
    NULL,
    1,
    NULL,
    2
),
(
    'Quản lý dịch hại',
    'Áp dụng các biện pháp quản lý dịch hại tổng hợp trong vườn cam theo VietGAP; sử dụng thuốc bảo vệ thực vật đúng quy định, đảm bảo an toàn cho người sản xuất, môi trường và sản phẩm.',
    35,
    true,
    false,
    1,
    'CARE',
    NULL,
    1,
    NULL,
    2
),
(
    'Thu hoạch',
    'Thu hoạch quả cam khi đạt độ chín thích hợp, đảm bảo thời gian cách ly thuốc bảo vệ thực vật. Trong quá trình thu hoạch tránh làm xây xát quả và hạn chế quả tiếp xúc trực tiếp với đất.',
    40,
    false,
    false,
    1,
    'HARVEST',
    NULL,
    NULL,
    NULL,
    2
),
(
    'Đóng gói',
    'Quả cam sau thu hoạch được làm sạch, phân loại và đóng gói bằng vật liệu phù hợp, đảm bảo vệ sinh an toàn thực phẩm theo yêu cầu VietGAP.',
    50,
    false,
    false,
    1,
    'POST_HARVEST',
    NULL,
    NULL,
    NULL,
    2
);
