INSERT INTO "step"
(name, description, "order", repeated, is_optional, min_logs, type, interval_date, min_day_duration, max_day_duration, crop_id)
VALUES
(
    'Chuẩn bị đất trồng',
    'Sau khi đào mương lên liếp để trồng chôm chôm, tiến hành đắp mô trên liếp. Mô đất có kích thước: mặt mô 0,7–0,8 m, đáy mô 1,0–1,2 m, chiều cao mô ≥ 0,5 m. Vật liệu đắp mô theo tỷ lệ 1/4 phân gà hoai + 3/4 đất màu mỡ. Công tác chuẩn bị mô hoàn chỉnh trước khi trồng 15–20 ngày.',
    11,
    false,
    true,
    1,
    'PREPARE',
    NULL,
    15,
    20,
    3
),
(
    'Đào lỗ và bón lót',
    'Trước khi trồng, đào lỗ giữa mô có kích thước bằng bầu đất cây con, trộn lớp đất đào với 50–100 g phân NPK (20.20.15 hoặc 15.15.15) và thuốc sát trùng theo khuyến cáo để bảo vệ bộ rễ tơ.',
    12,
    false,
    true,
    1,
    'PREPARE',
    NULL,
    NULL,
    NULL,
    3
),
(
    'Trồng cây',
    'Cắt bỏ đáy bầu, đặt cây vào hố và lấp đất ngang mặt bầu, không lấp cao hơn mặt bầu và không làm tổn thương cây con. Cắm cọc giữ cây khỏi đổ ngã và che bóng cho cây con, chú ý không che quá 50%.',
    20,
    false,
    true,
    1,
    'PLANTING',
    NULL,
    NULL,
    NULL,
    3
),
(
    'Tưới nước',
    'Tưới đủ nước cho cây chôm chôm, đặc biệt trong giai đoạn khô hạn; mùa mưa cần thoát nước kịp thời. Áp dụng các biện pháp tưới hiệu quả như tưới nhỏ giọt, tưới phun và giữ ẩm bằng tủ gốc.',
    31,
    true,
    false,
    1,
    'CARE',
    NULL,
    NULL,
    NULL,
    3
),
(
    'Bón phân',
    'Sử dụng phân bón theo nhu cầu của cây chôm chôm và kết quả phân tích đất. Phân hữu cơ phải được ủ hoai mục; sử dụng phân vô cơ đúng loại, đúng liều lượng theo từng giai đoạn sinh trưởng.',
    32,
    true,
    false,
    1,
    'CARE',
    NULL,
    NULL,
    NULL,
    3
),
(
    'Tỉa cành và tạo tán',
    'Tạo tán cho cây từ nhỏ bằng cách bấm ngọn khi cây ghép cao 70–100 cm, giữ lại 3–5 cành khỏe. Hàng năm sau thu hoạch tỉa bỏ cành sâu bệnh, cành vô hiệu, cành đan chéo để cây thông thoáng và phát triển tốt.',
    33,
    true,
    false,
    1,
    'CARE',
    NULL,
    NULL,
    NULL,
    3
),
(
    'Quản lý dịch hại',
    'Áp dụng quản lý dịch hại tổng hợp (IPM), chỉ sử dụng thuốc BVTV khi cần thiết, đúng ngưỡng gây hại và theo nguyên tắc 4 đúng. Thuốc BVTV phải nằm trong danh mục được phép sử dụng.',
    34,
    true,
    false,
    1,
    'CARE',
    NULL,
    NULL,
    NULL,
    3
),
(
    'Thu hoạch',
    'Thu hoạch chôm chôm khi quả đạt độ chín phù hợp, đảm bảo thời gian cách ly thuốc BVTV, tránh làm dập và xây xát quả.',
    40,
    false,
    false,
    1,
    'HARVEST',
    NULL,
    NULL,
    NULL,
    3
),
(
    'Đóng gói',
    'Quả chôm chôm sau thu hoạch được làm sạch, phân loại, đóng gói và bảo quản theo đúng yêu cầu vệ sinh, đảm bảo chất lượng và an toàn thực phẩm.',
    50,
    false,
    false,
    1,
    'POST_HARVEST',
    NULL,
    NULL,
    NULL,
    3
);
