INSERT INTO "step"
(name, description, "order", repeated, is_optional, min_logs, type, interval_date, min_day_duration, max_day_duration, crop_id)
VALUES
(
    'Chuẩn bị đất trồng',
    'Đất trồng chuối cần được làm sạch cỏ, cày bừa kỹ, lên liếp hoặc mô cao để tránh ngập úng. Đối với đất thấp cần đào mương thoát nước tốt trước khi trồng.',
    11,
    false,
    false,
    1,
    'PREPARE',
    NULL,
    NULL,
    NULL,
    4
),
(
    'Đào hố và bón lót',
    'Đào hố trồng chuối với kích thước phù hợp, trộn đất đào với phân chuồng hoai mục và phân lân để bón lót trước khi trồng nhằm cung cấp dinh dưỡng ban đầu cho cây.',
    12,
    false,
    false,
    1,
    'PREPARE',
    NULL,
    NULL,
    NULL,
    4
),
(
    'Trồng cây',
    'Trồng cây chuối giống khỏe mạnh, đặt cây đứng thẳng, lấp đất ngang cổ thân và nén chặt gốc để cây không bị nghiêng ngã.',
    20,
    false,
    false,
    1,
    'PLANTING',
    NULL,
    NULL,
    NULL,
    4
),
(
    'Tưới nước',
    'Cung cấp đủ nước cho cây chuối trong suốt quá trình sinh trưởng, đặc biệt vào mùa khô; đảm bảo đất luôn đủ ẩm nhưng không bị úng.',
    31,
    true,
    false,
    1,
    'CARE',
    NULL,
    NULL,
    NULL,
    4
),
(
    'Bón phân',
    'Bón phân cho chuối theo từng giai đoạn sinh trưởng, kết hợp phân hữu cơ và phân vô cơ nhằm đảm bảo cây sinh trưởng tốt và cho năng suất cao.',
    32,
    true,
    false,
    1,
    'CARE',
    NULL,
    NULL,
    NULL,
    4
),
(
    'Tỉa chồi và vệ sinh vườn',
    'Thường xuyên tỉa bỏ chồi vô hiệu, chỉ giữ lại số chồi cần thiết; kết hợp vệ sinh vườn để hạn chế sâu bệnh phát sinh.',
    33,
    true,
    false,
    1,
    'CARE',
    NULL,
    NULL,
    NULL,
    4
),
(
    'Quản lý sâu bệnh',
    'Áp dụng các biện pháp phòng trừ sâu bệnh tổng hợp, sử dụng thuốc bảo vệ thực vật đúng liều lượng, đúng thời điểm và đảm bảo thời gian cách ly.',
    34,
    true,
    false,
    1,
    'CARE',
    NULL,
    NULL,
    NULL,
    4
),
(
    'Thu hoạch',
    'Thu hoạch chuối khi buồng đạt độ già thích hợp, cắt buồng nhẹ nhàng để tránh làm dập quả và ảnh hưởng đến chất lượng.',
    40,
    false,
    false,
    1,
    'HARVEST',
    NULL,
    NULL,
    NULL,
    4
),
(
    'Xử lý và bảo quản sau thu hoạch',
    'Chuối sau thu hoạch được làm sạch, phân loại và bảo quản theo đúng yêu cầu kỹ thuật nhằm đảm bảo chất lượng và an toàn thực phẩm.',
    50,
    false,
    false,
    1,
    'POST_HARVEST',
    NULL,
    NULL,
    NULL,
    4
);
