INSERT INTO "step"
(name, description, "order", repeated, is_optional, min_logs, type, interval_date, min_day_duration, max_day_duration, crop_id)
VALUES
(
    'Đào hố và bón lót',
    'Đào hố trồng theo nguyên tắc đất xấu đào hố to, đất tốt đào hố nhỏ. Kích thước hố thông thường 0,8 x 0,8 x 0,6 m; đất xấu 1 x 1 x 0,8 m. Bón lót mỗi hố 30–50 kg phân chuồng, 0,7–1,0 kg supe lân và 0,5 kg vôi bột, trộn đều với đất đào lên rồi lấp lại. Chuẩn bị trước khi trồng 1 tháng.',
    10,
    false,
    true,
    1,
    'PREPARE',
    NULL,
    30,
    30,
    5
),
(
    'Trồng cây',
    'Khơi hố nhỏ giữa hố đào, xé bỏ túi bầu, đặt cây giống sao cho mặt bầu bằng hoặc thấp hơn mặt đất 2–3 cm, lấp đất và dùng tay nén chặt xung quanh gốc.',
    21,
    false,
    true,
    1,
    'PLANTING',
    NULL,
    NULL,
    NULL,
    5
),
(
    'Cắm cọc và tạo bồn giữ nước',
    'Cắm cọc và dùng dây mềm buộc cố định cây để tránh gió lay đứt rễ. Vun đất mặt xung quanh gốc tạo ụ hình lòng chảo, đường kính khoảng 1 m, gờ cao 20–25 cm so với mặt vườn.',
    22,
    false,
    true,
    1,
    'PLANTING',
    NULL,
    NULL,
    NULL,
    5
),
(
    'Tưới nước và tủ gốc sau trồng',
    'Sau khi trồng tưới đậm nước, tủ gốc giữ ẩm và hạn chế cỏ dại bằng rơm rạ hoặc cỏ khô.',
    23,
    false,
    true,
    1,
    'PLANTING',
    NULL,
    2,
    2,
    5
),
(
    'Tưới nước',
    'Tưới nước cho cây nhãn sau khi trồng và trong suốt quá trình sinh trưởng, đảm bảo đủ ẩm cho cây; mùa mưa cần chú ý thoát nước tốt.',
    31,
    true,
    false,
    1,
    'CARE',
    NULL,
    NULL,
    NULL,
    5
),
(
    'Bón phân',
    'Bón phân cho cây nhãn theo từng giai đoạn sinh trưởng và phát triển của cây, kết hợp phân hữu cơ và phân vô cơ nhằm đảm bảo năng suất và chất lượng quả.',
    32,
    true,
    false,
    1,
    'CARE',
    NULL,
    NULL,
    NULL,
    5
),
(
    'Cắt tỉa và tạo tán',
    'Thực hiện cắt tỉa cành để tạo tán cho cây nhãn, loại bỏ cành sâu bệnh, cành vô hiệu nhằm giúp cây thông thoáng và sinh trưởng tốt.',
    33,
    true,
    false,
    1,
    'CARE',
    NULL,
    NULL,
    NULL,
    5
),
(
    'Quản lý sâu bệnh',
    'Áp dụng các biện pháp quản lý sâu bệnh tổng hợp, sử dụng thuốc bảo vệ thực vật đúng liều lượng, đúng thời điểm và đảm bảo thời gian cách ly.',
    34,
    true,
    false,
    1,
    'CARE',
    NULL,
    NULL,
    NULL,
    5
),
(
    'Thu hoạch',
    'Thu hoạch nhãn khi quả đạt độ chín thích hợp, thu hái nhẹ nhàng để tránh làm dập quả và ảnh hưởng đến chất lượng.',
    40,
    false,
    false,
    1,
    'HARVEST',
    NULL,
    NULL,
    NULL,
    5
),
(
    'Xử lý và bảo quản sau thu hoạch',
    'Quả nhãn sau thu hoạch được làm sạch, phân loại, đóng gói và bảo quản theo đúng yêu cầu kỹ thuật nhằm đảm bảo chất lượng và an toàn thực phẩm.',
    50,
    false,
    false,
    1,
    'POST_HARVEST',
    NULL,
    NULL,
    NULL,
    5
);
