INSERT INTO "step"
(name, description, "order", repeated, is_optional, min_logs, type, interval_date, min_day_duration, max_day_duration, crop_id)
VALUES
(
    'Chuẩn bị đất trồng',
    'Tiến hành đắp mô trên liếp, mô đất có kích thước mặt mô 0,7–0,8 m, đáy mô 1,0–1,2 m, chiều cao mô ≥ 0,5 m. Vật liệu đắp mô theo tỷ lệ 1/4 phân chuồng ủ hoai và 3/4 đất màu mỡ. Đối với vùng đất cao, trồng ngang bằng mặt đất và đánh rãnh xung quanh gốc để dễ tưới tiêu và thoát nước. Công tác chuẩn bị mô hoàn chỉnh trước trồng 15–20 ngày.',
    11,
    false,
    true,
    1,
    'PREPARE',
    NULL,
    15,
    20,
    6
),
(
    'Đào hố và bón lót',
    'Đào hố trên mô đã đắp với kích thước 0,3 x 0,3 x 0,3 m. Trộn lớp đất đào với 50–100 g phân NPK (20-20-15 hoặc 15-15-15) và thuốc sát trùng theo khuyến cáo để bảo vệ bộ rễ tơ.',
    12,
    false,
    true,
    1,
    'PREPARE',
    NULL,
    NULL,
    NULL,
    6
),
(
    'Trồng cây',
    'Cắt bỏ đáy vật liệu làm bầu đất, đặt cây vào hố trồng và lấp đất vừa ngang mặt bầu, không lấp cao hơn mặt bầu và không làm tổn thương cây con. Cắm cọc giữ cây khỏi đổ ngã và che bóng cho cây con, chú ý không che quá 50% ánh sáng mặt trời.',
    20,
    false,
    true,
    1,
    'PLANTING',
    NULL,
    NULL,
    NULL,
    6
),
(
    'Tưới nước và giữ ẩm',
    'Quản lý nước tưới phù hợp từng giai đoạn sinh trưởng. Sử dụng rơm hoặc cỏ khô phủ kín mô đất lớp dày 10–20 cm, cách gốc 10–50 cm để giữ ẩm và hạn chế mầm bệnh tấn công vào gốc.',
    31,
    true,
    false,
    1,
    'CARE',
    NULL,
    NULL,
    NULL,
    6
),
(
    'Bón phân',
    'Bón phân hữu cơ và phân vô cơ theo từng giai đoạn sinh trưởng. Không sử dụng phân chuồng chưa hoai mục và sử dụng phân bón được phép lưu hành tại Việt Nam.',
    32,
    true,
    false,
    1,
    'CARE',
    NULL,
    NULL,
    NULL,
    6
),
(
    'Tỉa cành và tạo tán',
    'Thực hiện tỉa cành và tạo tán ngay từ năm thứ nhất. Tỉa bỏ chồi mọc từ gốc ghép, cành mọc thấp và mọc đứng, chỉ để một thân chính thẳng đứng, các cành cấp 1 phân bố đều và thông thoáng.',
    33,
    true,
    false,
    1,
    'CARE',
    NULL,
    NULL,
    NULL,
    6
),
(
    'Quản lý dịch hại',
    'Áp dụng các biện pháp quản lý dịch hại tổng hợp, sử dụng thuốc bảo vệ thực vật theo nguyên tắc VietGAP, đảm bảo thời gian cách ly và an toàn thực phẩm.',
    34,
    true,
    false,
    1,
    'CARE',
    NULL,
    NULL,
    NULL,
    6
),
(
    'Thu hoạch',
    'Thu hoạch sầu riêng khi quả đạt độ chín phù hợp, đảm bảo thời gian cách ly thuốc bảo vệ thực vật và hạn chế gây tổn thương cơ giới cho quả.',
    40,
    false,
    false,
    1,
    'HARVEST',
    NULL,
    NULL,
    NULL,
    6
),
(
    'Xử lý sau thu hoạch',
    'Xử lý, bảo quản và vận chuyển quả sau thu hoạch đảm bảo vệ sinh, không gây ô nhiễm và giữ chất lượng sản phẩm.',
    50,
    false,
    false,
    1,
    'POST_HARVEST',
    NULL,
    NULL,
    NULL,
    6
);
