INSERT INTO "step" 
(name, description, "order", repeated, is_optional, min_logs, type, interval_date, min_day_duration, max_day_duration, crop_id)
VALUES
(
    'Chuẩn bị hố trồng',
    'Đào hố trồng vải theo nguyên tắc đất xấu đào hố to, đất tốt đào hố nhỏ. Kích thước hố thông thường 0,8 x 0,8 x 0,6 m; vùng đồi đất xấu đào hố 1 x 1 x 0,8 m. Bón lót cho mỗi hố 30–50 kg phân chuồng, 0,7–1,0 kg supe lân và 0,5 kg vôi bột, trộn đều với đất mặt và lấp lại hố trước khi trồng 1 tháng.',
    10,
    false,
    true,
    1,
    'PREPARE',
    NULL,
    30,
    NULL,
    8
),
(
    'Trồng cây',
    'Khơi hố nhỏ giữa hố đã đào, xé bỏ túi bầu và đặt cây giống sao cho mặt bầu bằng hoặc thấp hơn mặt đất 2–3 cm. Lấp đất và nén chặt quanh gốc, cắm cọc cố định cây, vun đất tạo ụ hình lòng chảo đường kính khoảng 1 m, gờ cao 20–25 cm.',
    21,
    false,
    true,
    1,
    'PLANTING',
    NULL,
    NULL,
    NULL,
    8
),
(
    'Chăm sóc sau trồng',
    'Sau trồng cắm cọc giữ cây, tưới đẫm nước và tủ gốc bằng rơm rạ hoặc cỏ khô để giữ ẩm và hạn chế cỏ dại. Tháng đầu tưới nước 2 ngày/lần; các tháng tiếp theo điều chỉnh theo thời tiết, nắng nóng cần tưới thường xuyên và che nắng cho cây.',
    22,
    false,
    true,
    1,
    'PLANTING',
    NULL,
    NULL,
    NULL,
    8
),
(
    'Tưới nước',
    'Thực hiện tưới nước cho cây vải theo từng giai đoạn sinh trưởng. Áp dụng tưới phun mưa do cây có bộ rễ lan rộng và ăn sâu; điều chỉnh chu kỳ tưới theo lượng mưa và độ giữ ẩm của đất.',
    31,
    true,
    false,
    1,
    'CARE',
    NULL,
    NULL,
    NULL,
    8
),
(
    'Bón phân',
    'Quản lý và bón phân cho cây vải theo từng giai đoạn sinh trưởng, kết hợp phân hữu cơ và phân vô cơ theo hướng dẫn kỹ thuật, đảm bảo hiệu quả và an toàn theo VietGAP.',
    32,
    true,
    false,
    1,
    'CARE',
    NULL,
    NULL,
    NULL,
    8
),
(
    'Cắt tỉa',
    'Cắt tỉa tạo hình giai đoạn kiến thiết cơ bản và cắt tỉa giai đoạn kinh doanh nhằm khống chế tán cây, loại bỏ cành yếu, cành bị che khuất và tạo điều kiện thuận lợi cho ra hoa, đậu quả.',
    33,
    true,
    false,
    1,
    'CARE',
    NULL,
    NULL,
    NULL,
    8
),
(
    'Quản lý sâu bệnh',
    'Quản lý cỏ dại và phòng trừ sâu bệnh hại cây vải bằng các biện pháp canh tác, sinh học và hóa học theo quy định VietGAP, đảm bảo an toàn và hiệu quả.',
    34,
    true,
    false,
    1,
    'CARE',
    NULL,
    NULL,
    NULL,
    8
),
(
    'Thu hoạch',
    'Thu hoạch quả vải khi đạt độ chín phù hợp, đảm bảo chất lượng quả và tuân thủ các yêu cầu về an toàn thực phẩm theo VietGAP.',
    40,
    false,
    false,
    1,
    'HARVEST',
    NULL,
    NULL,
    NULL,
    8
),
(
    'Xử lý sau thu hoạch',
    'Thực hiện các biện pháp xử lý, bảo quản và quản lý sản phẩm sau thu hoạch theo quy trình VietGAP nhằm đảm bảo chất lượng và an toàn sản phẩm.',
    50,
    false,
    false,
    1,
    'POST_HARVEST',
    NULL,
    NULL,
    NULL,
    8
);
