INSERT INTO "step" (name, description, "order", repeated, is_optional, min_logs, type, interval_date, min_day_duration, max_day_duration, crop_id)
VALUES
(
    'Chuẩn bị đất trồng',
    'Vùng đất thấp phải trồng trên mô, mô rộng 0,6–1 m, cao 50–70 cm so với mặt nước trong vườn; sau đó bồi mô và làm liếp dần dần. Vùng đất cao phải đào hố trồng kích thước thông thường 0,8 x 0,8 x 0,6 m; vùng đồi đất xấu đào hố 1 x 1 x 0,8 m. Hố trồng cần chuẩn bị trước khi trồng 2–4 tuần.',
    11,
    false,
    true,
    1,
    'PREPARE',
    NULL,
    14,
    28,
    9
),
(
    'Bón lót',
    'Bón lót 10–20 kg phân chuồng hoai mục và 200 g NPK 16-16-8 hoặc 0,5 kg phân Super lân; nếu vùng đất chua phèn thì sử dụng lân nung chảy.',
    12,
    false,
    true,
    1,
    'PREPARE',
    NULL,
    NULL,
    NULL,
    9
),
(
    'Trồng cây',
    'Dùng dao cắt đáy bầu và đặt cây xuống giữa mô, giữ mặt bầu nhô cao 3–5 cm so với mặt mô; cho hỗn hợp đất vào xung quanh bầu cây, ém nhẹ, kéo bao nilon lên và lấp đất ngang mặt bầu. Sau khi trồng cắm 2 cọc chéo hình chữ X, buộc dây tránh lay gốc, tủ rơm rác mục quanh mô và tưới nước giữ ẩm cho cây. Nên trồng vào đầu mùa mưa; nếu chủ động nước tưới có thể trồng trong mùa khô, thời vụ tùy điều kiện từng địa phương.',
    20,
    false,
    true,
    1,
    'PLANTING',
    NULL,
    NULL,
    NULL,
    9
),
(
    'Bón phân',
    'Sử dụng phân hữu cơ và phân vô cơ theo từng giai đoạn sinh trưởng của cây xoài. Phân bón và hóa chất bổ sung phải có nguồn gốc rõ ràng, nằm trong danh mục cho phép sử dụng và bón theo đúng kỹ thuật được hướng dẫn.',
    31,
    true,
    false,
    1,
    'CARE',
    NULL,
    1,
    NULL,
    9
),
(
    'Tưới nước',
    'Áp dụng kỹ thuật tưới phù hợp từng giai đoạn sinh trưởng của cây, đảm bảo đủ ẩm và thoát nước tốt.',
    32,
    true,
    false,
    1,
    'CARE',
    NULL,
    1,
    NULL,
    9
),
(
    'Tỉa cành và tạo tán',
    'Thực hiện tỉa cành tạo tán nhằm tạo bộ khung cây cân đối, thông thoáng, hạn chế sâu bệnh và thuận lợi cho chăm sóc, thu hoạch.',
    33,
    true,
    false,
    1,
    'CARE',
    NULL,
    1,
    NULL,
    9
),
(
    'Xử lý ra hoa',
    'Áp dụng các biện pháp xử lý ra hoa phù hợp với điều kiện canh tác và sinh trưởng của cây xoài, đảm bảo ra hoa tập trung và đúng thời vụ.',
    34,
    true,
    false,
    1,
    'CARE',
    NULL,
    1,
    NULL,
    9
),
(
    'Các chăm sóc khác',
    'Thực hiện quản lý cỏ, tăng đậu quả, hạn chế rụng quả non, tỉa quả và bao quả theo hướng dẫn kỹ thuật nhằm nâng cao năng suất và chất lượng quả.',
    35,
    true,
    false,
    1,
    'CARE',
    NULL,
    1,
    NULL,
    9
),
(
    'Quản lý dịch hại',
    'Quản lý hóa chất và thuốc bảo vệ thực vật theo nguyên tắc an toàn, đúng danh mục cho phép; áp dụng các biện pháp quản lý dịch hại tổng hợp nhằm hạn chế sâu bệnh gây hại.',
    36,
    true,
    false,
    1,
    'CARE',
    NULL,
    1,
    NULL,
    9
),
(
    'Thu hoạch',
    'Thu hoạch quả xoài khi đạt độ chín phù hợp, đảm bảo thời gian cách ly thuốc bảo vệ thực vật và tránh gây tổn thương cơ học cho quả.',
    40,
    false,
    false,
    1,
    'HARVEST',
    NULL,
    NULL,
    NULL,
    9
),
(
    'Xử lý sau thu hoạch',
    'Thực hiện phân loại, làm sạch và đóng gói quả xoài sau thu hoạch đảm bảo vệ sinh, hạn chế nhiễm bẩn và đáp ứng yêu cầu truy xuất nguồn gốc.',
    50,
    false,
    false,
    1,
    'POST_HARVEST',
    NULL,
    NULL,
    NULL,
    9
);

