name: Deploy Dev

on:
    push:
        branches:
            - dev
            - devops

    pull_request:
        branches:
            - dev

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Node setup
              uses: actions/setup-node@v5
              with:
                node-version: 24
            
            - name: Install dependencies
              run: npm install

            - name: Run lint
              run: npm run lint
            
            - name: Run build
              run: npm run build
            
            - name: Run tests
              run: npm run test

    deploy:
        needs: test
        runs-on: self-hosted
        if: github.event_name == 'push'
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Create .env
              run: |
                touch .env
                echo "{{secrets.DEVELOPMENT_SECRETS}}" >> .env
                

