name: PR check

on:
    push:
        branches:
            - master
            - dev

    pull_request:
        branches:
            - master
            - dev

jobs:
    lint-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Node setup
              uses: actions/setup-node@v5
              with:
                node-version: 24
            
            - name: Install dependencies
              run: npm install

            - name: Run lint
              run: npm run lint
            
            - name: Run tests
              run: npm run test
